### ISSUE TITLE
Change name of repo

### ISSUE THREAD

**Issue by NadyaNayme** [mushishi78/womb#1]
A "womb" is not a "wrapper". It's part of the female reproductive system and is where development and for you to trivialize a part of a woman's body like that is wrong. The repo may as well be called "ballsack".

**Comment by mushishi78** [comment]
I honestly didn't think it was inappropriate and I'm sorry that it bothers you. Perhaps I'm not very good at naming things. I'd be open to name suggestions, but they have to be available on RubyGems.

**Comment by mushishi78** [comment]
Oh wait. I see your just trying to be annoying because of [this issue](https://github.com/NARKOZ/hacker-scripts/issues/14) thread. In that case, I'm not going to take you seriously.

**Comment by AJMcKane** [comment]
TopKek

**Comment by aerisdies** [comment]
Rekt

**Comment by NadyaNayme** [comment]
> I see you're just trying to be annoying because of this issue thread. In that case, I'm not going to take you seriously.

I had hesitations about posting in that thread until after I had gotten you to change the name. Given your initial response, I would have gotten away with it. Drat.

I commend you for being consistent and, furthermore, respectful and straightforward with me even after discovering my intentions.

Have a happy holidays,
なだや

**Comment by Liareth** [comment]
+1 to reopen this issue. I thought it didn't matter who raised a problem, troll or no? As a woman I am deeply offended that you would violate the sanctity of the temple that is my body. I feel marginalized and trivialised. This is offensive to women because it makes light of a lovely internal body part and it is offensive to men because it implies that men can't have anything inside of them.
